version: "3"
services:

  spring-app:
    env_file:
      .env
    build:
      context: .
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      .env
    ports:
      - "3307:3306"
    restart: always