spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

chatgpt:
  api-key: